### PR TITLE
use legacy deps

### PR DESCRIPTION
**Pull request by cnell-usgs**
reverting conflicts with `eslint` and updating `webpack`. the main errors were with peer dependencies, which required reverting to legacy peer dependencies to build the page. This is appearing as an issue suddenly because of the upgrade in `npm` versions. The most recent versions of `npm` have stricter dependency rules, which we will avoid addressing at this time.

### CODE REVIEW

**Comment by cnell-usgs** [comment]
@hcorson-dosch please review this by pulling down the changes, deleting your current `node_modules` folder and running `npm install`. If you are able to build the page via `npm run serve` then we are good to go.

**Comment by hcorson-dosch-usgs** [comment]
@ceenell - given the recently troubleshooting with Althea, did you still want this PR reviewed and merged in, or is it no longer necessary?

**Comment by cnell-usgs** [comment]
were you able to get the repo running using node v 14.17.0?

**Comment by hcorson-dosch-usgs** [comment]
I'm mostly there now, with node `v14.17.0` and the switch to git bash as my default shell in VS code (instead of Windows powershell - which hadn't been an issue previously). Just missing some `.svg` and `.png` files in `assets/images` that are dependencies for the `DragNDrop` component, but if I add the `rain` component instead, the page builds!

**Comment by cnell-usgs** [comment]
Updated to switch out to a different component

**Review by hcorson-dosch-usgs — APPROVED** [review]
Good to go! Thanks for figuring out how to get this running again.

**Pull request merged**
